version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.18
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - run:
          name: "Push"
          command: |
            make push
