version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - run:
          name: "Build"
          command: |
            make build
