version: 2.1

# Dynamic Configuration
setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.2

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            go/services/service1/.* run-build-service1-job true
            go/services/service2/.* run-build-service2-job true
            go/pkg/.* run-build-pkg-job true
          base-revision: main
          config-path: .circleci/continue_config.yml
