version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/go:1.18
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run:
          name: Deploy
          command: make deploy

workflows:
  build-and-deploy:
    jobs:
      - build:
          context:
            - DockerHub
      - deploy:
          context:
            - DockerHub
          requires:
            - build
          filters:
            branches:
              only:
                - /.*/
